"""Generating the entry points that live on the target system.

The target rootfs is built by mmdebstrap from distribution packages, not by
pip, so there is no console-script machinery to lean on. Instead the package
tree is copied to :data:`TARGET_LIB` and small shims are generated that put
that directory on ``sys.path`` and call into it.

Why shims rather than copying a self-contained script per entry point: the
logic stays in one importable, testable place, and the thing sitting in
``/etc/kernel/install.d/`` is small enough to read in full. The cost is that
the target needs the package present, which the rootfs build guarantees — and
which :func:`verify_installed` re-checks on the built image rather than
assuming.
"""

from __future__ import annotations

from pathlib import Path

#: Where the package is copied to on the target system.
TARGET_LIB = "/usr/local/lib/ubuntu-uki-iso"

#: The console script.
TARGET_BIN = "/usr/local/bin/ubuntu-uki-iso"

_SHIM = '''#!/usr/bin/env python3
"""{description}

Generated by ubuntu-uki-iso — edits here are overwritten on the next build.
The implementation is in {module}.
"""

import sys

sys.path.insert(0, {lib!r})

from {module} import main  # noqa: E402

if __name__ == "__main__":
    sys.exit(main())
'''


def render_shim(module: str, description: str) -> str:
    """A standalone executable that calls ``<module>.main()``."""
    return _SHIM.format(module=module, description=description, lib=TARGET_LIB)


def write_shim(path: Path, module: str, description: str) -> Path:
    """Write a shim and make it executable.

    Mode 0755 explicitly: these run from kernel-install and from the live
    environment's PATH, and a shim that is not executable fails as "command not
    found", which points nowhere useful.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_shim(module, description), encoding="utf-8")
    path.chmod(0o755)
    return path


#: The kernel-install plugins, as (filename, module, description).
#:
#: Name order is execution order: kernel-install runs the scripts in
#: /etc/kernel/install.d/ sorted by name. 90-uki-copy.install (shipped by
#: systemd) writes the versioned UKI, 95 refreshes the firmware fallback, and
#: 99 prunes. Pruning before the copy would delete the wrong set.
KERNEL_INSTALL_PLUGINS: tuple[tuple[str, str, str], ...] = (
    (
        "95-ubuntu-uki-iso-fallback.install",
        "ubuntu_uki_iso.ukis.fallback",
        "Copy the new UKI to \\EFI\\BOOT\\BOOTX64.EFI, the path firmware boots "
        "with no configuration at all.",
    ),
    (
        "99-ubuntu-uki-iso-retention.install",
        "ubuntu_uki_iso.ukis.retention",
        "Prune old UKIs from \\EFI\\Linux so the ESP does not fill up.",
    ),
)


def install_kernel_install_plugins(root: Path) -> list[Path]:
    """Write every kernel-install plugin into ``root``."""
    written = []
    plugin_dir = root / "etc/kernel/install.d"
    for filename, module, description in KERNEL_INSTALL_PLUGINS:
        written.append(write_shim(plugin_dir / filename, module, description))
    return written
